//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurClient.Windows.FurService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FurRequest", Namespace="http://schemas.studiofarma.it/WebDPC/FurRequest")]
    [System.SerializableAttribute()]
    public partial class FurRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodiceAslField;
        
        private string CodiceFarmaciaASLField;
        
        private string MeseField;
        
        private string AnnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceAsl {
            get {
                return this.CodiceAslField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceAslField, value) != true)) {
                    this.CodiceAslField = value;
                    this.RaisePropertyChanged("CodiceAsl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodiceFarmaciaASL {
            get {
                return this.CodiceFarmaciaASLField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFarmaciaASLField, value) != true)) {
                    this.CodiceFarmaciaASLField = value;
                    this.RaisePropertyChanged("CodiceFarmaciaASL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mese {
            get {
                return this.MeseField;
            }
            set {
                if ((object.ReferenceEquals(this.MeseField, value) != true)) {
                    this.MeseField = value;
                    this.RaisePropertyChanged("Mese");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Anno {
            get {
                return this.AnnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnoField, value) != true)) {
                    this.AnnoField = value;
                    this.RaisePropertyChanged("Anno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distinta", Namespace="http://schemas.studiofarma.it/WebDPC/FurService/Distinta")]
    [System.SerializableAttribute()]
    public partial class Distinta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeseCompetenzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnnoCompetenzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalePrezzoPubblicoProdottiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImportoCompensoNettoIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImportoTicketRiscossiLordoIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImportoTicketRiscossiNettoIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotaleImponibileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotaleIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotaleFatturatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroRicetteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroProdottiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FurClient.Windows.FurService.Ricetta[] RicetteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeseCompetenza {
            get {
                return this.MeseCompetenzaField;
            }
            set {
                if ((object.ReferenceEquals(this.MeseCompetenzaField, value) != true)) {
                    this.MeseCompetenzaField = value;
                    this.RaisePropertyChanged("MeseCompetenza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string AnnoCompetenza {
            get {
                return this.AnnoCompetenzaField;
            }
            set {
                if ((object.ReferenceEquals(this.AnnoCompetenzaField, value) != true)) {
                    this.AnnoCompetenzaField = value;
                    this.RaisePropertyChanged("AnnoCompetenza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal TotalePrezzoPubblicoProdotti {
            get {
                return this.TotalePrezzoPubblicoProdottiField;
            }
            set {
                if ((this.TotalePrezzoPubblicoProdottiField.Equals(value) != true)) {
                    this.TotalePrezzoPubblicoProdottiField = value;
                    this.RaisePropertyChanged("TotalePrezzoPubblicoProdotti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal ImportoCompensoNettoIva {
            get {
                return this.ImportoCompensoNettoIvaField;
            }
            set {
                if ((this.ImportoCompensoNettoIvaField.Equals(value) != true)) {
                    this.ImportoCompensoNettoIvaField = value;
                    this.RaisePropertyChanged("ImportoCompensoNettoIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal ImportoTicketRiscossiLordoIva {
            get {
                return this.ImportoTicketRiscossiLordoIvaField;
            }
            set {
                if ((this.ImportoTicketRiscossiLordoIvaField.Equals(value) != true)) {
                    this.ImportoTicketRiscossiLordoIvaField = value;
                    this.RaisePropertyChanged("ImportoTicketRiscossiLordoIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal ImportoTicketRiscossiNettoIva {
            get {
                return this.ImportoTicketRiscossiNettoIvaField;
            }
            set {
                if ((this.ImportoTicketRiscossiNettoIvaField.Equals(value) != true)) {
                    this.ImportoTicketRiscossiNettoIvaField = value;
                    this.RaisePropertyChanged("ImportoTicketRiscossiNettoIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal TotaleImponibile {
            get {
                return this.TotaleImponibileField;
            }
            set {
                if ((this.TotaleImponibileField.Equals(value) != true)) {
                    this.TotaleImponibileField = value;
                    this.RaisePropertyChanged("TotaleImponibile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal TotaleIva {
            get {
                return this.TotaleIvaField;
            }
            set {
                if ((this.TotaleIvaField.Equals(value) != true)) {
                    this.TotaleIvaField = value;
                    this.RaisePropertyChanged("TotaleIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal TotaleFatturato {
            get {
                return this.TotaleFatturatoField;
            }
            set {
                if ((this.TotaleFatturatoField.Equals(value) != true)) {
                    this.TotaleFatturatoField = value;
                    this.RaisePropertyChanged("TotaleFatturato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int NumeroRicette {
            get {
                return this.NumeroRicetteField;
            }
            set {
                if ((this.NumeroRicetteField.Equals(value) != true)) {
                    this.NumeroRicetteField = value;
                    this.RaisePropertyChanged("NumeroRicette");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int NumeroProdotti {
            get {
                return this.NumeroProdottiField;
            }
            set {
                if ((this.NumeroProdottiField.Equals(value) != true)) {
                    this.NumeroProdottiField = value;
                    this.RaisePropertyChanged("NumeroProdotti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public FurClient.Windows.FurService.Ricetta[] Ricette {
            get {
                return this.RicetteField;
            }
            set {
                if ((object.ReferenceEquals(this.RicetteField, value) != true)) {
                    this.RicetteField = value;
                    this.RaisePropertyChanged("Ricette");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ricetta", Namespace="http://schemas.studiofarma.it/WebDPC/FurService/Ricetta")]
    [System.SerializableAttribute()]
    public partial class Ricetta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgressivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AslAssistitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceRegionaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceRicettaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSpedizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OnereFarmaciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OnereGrossistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEsenzioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TicketRiscossoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceFiscaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DifformeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataNascitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FurClient.Windows.FurService.Prodotto[] ProdottiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Progressivo {
            get {
                return this.ProgressivoField;
            }
            set {
                if ((this.ProgressivoField.Equals(value) != true)) {
                    this.ProgressivoField = value;
                    this.RaisePropertyChanged("Progressivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Iup {
            get {
                return this.IupField;
            }
            set {
                if ((object.ReferenceEquals(this.IupField, value) != true)) {
                    this.IupField = value;
                    this.RaisePropertyChanged("Iup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AslAssistito {
            get {
                return this.AslAssistitoField;
            }
            set {
                if ((object.ReferenceEquals(this.AslAssistitoField, value) != true)) {
                    this.AslAssistitoField = value;
                    this.RaisePropertyChanged("AslAssistito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CodiceRegionale {
            get {
                return this.CodiceRegionaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceRegionaleField, value) != true)) {
                    this.CodiceRegionaleField = value;
                    this.RaisePropertyChanged("CodiceRegionale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CodiceRicetta {
            get {
                return this.CodiceRicettaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceRicettaField, value) != true)) {
                    this.CodiceRicettaField = value;
                    this.RaisePropertyChanged("CodiceRicetta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DataSpedizione {
            get {
                return this.DataSpedizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSpedizioneField, value) != true)) {
                    this.DataSpedizioneField = value;
                    this.RaisePropertyChanged("DataSpedizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string DataMedico {
            get {
                return this.DataMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataMedicoField, value) != true)) {
                    this.DataMedicoField = value;
                    this.RaisePropertyChanged("DataMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal OnereFarmacia {
            get {
                return this.OnereFarmaciaField;
            }
            set {
                if ((this.OnereFarmaciaField.Equals(value) != true)) {
                    this.OnereFarmaciaField = value;
                    this.RaisePropertyChanged("OnereFarmacia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal OnereGrossista {
            get {
                return this.OnereGrossistaField;
            }
            set {
                if ((this.OnereGrossistaField.Equals(value) != true)) {
                    this.OnereGrossistaField = value;
                    this.RaisePropertyChanged("OnereGrossista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string TipoEsenzione {
            get {
                return this.TipoEsenzioneField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEsenzioneField, value) != true)) {
                    this.TipoEsenzioneField = value;
                    this.RaisePropertyChanged("TipoEsenzione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal TicketRiscosso {
            get {
                return this.TicketRiscossoField;
            }
            set {
                if ((this.TicketRiscossoField.Equals(value) != true)) {
                    this.TicketRiscossoField = value;
                    this.RaisePropertyChanged("TicketRiscosso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string CodiceFiscale {
            get {
                return this.CodiceFiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFiscaleField, value) != true)) {
                    this.CodiceFiscaleField = value;
                    this.RaisePropertyChanged("CodiceFiscale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> Difforme {
            get {
                return this.DifformeField;
            }
            set {
                if ((this.DifformeField.Equals(value) != true)) {
                    this.DifformeField = value;
                    this.RaisePropertyChanged("Difforme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string DataNascita {
            get {
                return this.DataNascitaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataNascitaField, value) != true)) {
                    this.DataNascitaField = value;
                    this.RaisePropertyChanged("DataNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Sesso {
            get {
                return this.SessoField;
            }
            set {
                if ((object.ReferenceEquals(this.SessoField, value) != true)) {
                    this.SessoField = value;
                    this.RaisePropertyChanged("Sesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public FurClient.Windows.FurService.Prodotto[] Prodotti {
            get {
                return this.ProdottiField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdottiField, value) != true)) {
                    this.ProdottiField = value;
                    this.RaisePropertyChanged("Prodotti");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prodotto", Namespace="http://schemas.studiofarma.it/WebDPC/FurService/Prodotto")]
    [System.SerializableAttribute()]
    public partial class Prodotto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinsanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrezzoPubblicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AliquotaIvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrezzoAcquistoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercentualeFarmaciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercentualeGrossistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OnereProdottoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Minsan {
            get {
                return this.MinsanField;
            }
            set {
                if ((object.ReferenceEquals(this.MinsanField, value) != true)) {
                    this.MinsanField = value;
                    this.RaisePropertyChanged("Minsan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal PrezzoPubblico {
            get {
                return this.PrezzoPubblicoField;
            }
            set {
                if ((this.PrezzoPubblicoField.Equals(value) != true)) {
                    this.PrezzoPubblicoField = value;
                    this.RaisePropertyChanged("PrezzoPubblico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal AliquotaIva {
            get {
                return this.AliquotaIvaField;
            }
            set {
                if ((this.AliquotaIvaField.Equals(value) != true)) {
                    this.AliquotaIvaField = value;
                    this.RaisePropertyChanged("AliquotaIva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal PrezzoAcquisto {
            get {
                return this.PrezzoAcquistoField;
            }
            set {
                if ((this.PrezzoAcquistoField.Equals(value) != true)) {
                    this.PrezzoAcquistoField = value;
                    this.RaisePropertyChanged("PrezzoAcquisto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal PercentualeFarmacia {
            get {
                return this.PercentualeFarmaciaField;
            }
            set {
                if ((this.PercentualeFarmaciaField.Equals(value) != true)) {
                    this.PercentualeFarmaciaField = value;
                    this.RaisePropertyChanged("PercentualeFarmacia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal PercentualeGrossista {
            get {
                return this.PercentualeGrossistaField;
            }
            set {
                if ((this.PercentualeGrossistaField.Equals(value) != true)) {
                    this.PercentualeGrossistaField = value;
                    this.RaisePropertyChanged("PercentualeGrossista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal OnereProdotto {
            get {
                return this.OnereProdottoField;
            }
            set {
                if ((this.OnereProdottoField.Equals(value) != true)) {
                    this.OnereProdottoField = value;
                    this.RaisePropertyChanged("OnereProdotto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DpcFaultDetail", Namespace="http://schemas.studiofarma.it/WebDPC/DpcFaultDetail")]
    [System.SerializableAttribute()]
    public partial class DpcFaultDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.studiofarma.it/WebDPC/FurService", ConfigurationName="FurService.IFurService")]
    public interface IFurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.studiofarma.it/WebDPC/FurService/IFurService/GetFUR", ReplyAction="http://schemas.studiofarma.it/WebDPC/FurService/IFurService/GetFURResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FurClient.Windows.FurService.DpcFaultDetail), Action="http://schemas.studiofarma.it/WebDPC/FurService/IFurService/GetFURDpcFaultDetailF" +
            "ault", Name="DpcFaultDetail", Namespace="http://schemas.studiofarma.it/WebDPC/DpcFaultDetail")]
        FurClient.Windows.FurService.Distinta GetFUR(FurClient.Windows.FurService.FurRequest Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFurServiceChannel : FurClient.Windows.FurService.IFurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FurServiceClient : System.ServiceModel.ClientBase<FurClient.Windows.FurService.IFurService>, FurClient.Windows.FurService.IFurService {
        
        public FurServiceClient() {
        }
        
        public FurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FurClient.Windows.FurService.Distinta GetFUR(FurClient.Windows.FurService.FurRequest Request) {
            return base.Channel.GetFUR(Request);
        }
    }
}
